---
title: "Laboratorio 5"
format: pdf
editor: visual
---

## Instrucciones

Este laboratorio hace referencia a temas abordados en clase sobre regresión logística. Tienes la opción de contestarlo en equipos de hasta 3 personas (máx.) o de manera individual. El archivo con las respuestas lo debes enviar por email a mi correo electrónico (sergio.bejar@cide.edu) a más tardar el sábado 25 de mayo, 2023 a las 12:00pm.

La base de datos que vamos a utilizar se encuentra en el folder "Files" del repositorio Github de la clase y se llama ("admision.csv").

## Ejercicio: Determinantes de Admisión a Programa de Posgrado

En este ejercicio analizaremos que variables influyen en la decisión de programas de posgrado en EEUU de admitir a un estudiante o no.  En particular, vamos a asumir que la probabilidad de ser admitido a un programa de posgrado (admit) está dada en función de la calificación obtenida por el solicitante en el GRE (gre), el promedio de calificaciones en la licenciatura (gpa) y el ránking de la universidad en cuestión (rank). 

1. Estima un modelo logit de la especificación descrita. 

2. Interpreta los coeficientes obtenidos al estimar el modelo en (1). 

3. Calcula e interpreta la razón de momios (Odds Ratio) de los coeficientes de tu modelo. 

4. Calcula e interpreta las probabilidades de los coeficientes de tu modelo. 

5. Grafica el efecto de la variable gre en la variable dependiente. 

6. Evalúa tu modelo usando una prueba Likelihood Ratio. 

7. ¿Cuál es la precisión del modelo estimado en (1)?  
